/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package me.abdurkhalid.ems;

import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class UserTypeChange extends javax.swing.JFrame {
    private static EmployeeInfo theEmployee;

    /**
     * Creates new form UserTypeChange
     */
    public UserTypeChange(EmployeeInfo employee) {
        initComponents();
        this.theEmployee = employee;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fullTimeChange = new javax.swing.JButton();
        partTimeChange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("What Is The Employee Type You Would Like To Convert To?");

        fullTimeChange.setText("Full Time");
        fullTimeChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeChangeActionPerformed(evt);
            }
        });

        partTimeChange.setText("Part Time");
        partTimeChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partTimeChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(fullTimeChange)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(partTimeChange)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeChange)
                    .addComponent(partTimeChange))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullTimeChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeChangeActionPerformed
        try{
        if (theEmployee instanceof FullTimeEmployee){
        JOptionPane.showMessageDialog(null,"The employee is already a full time employee!");
        }
        else if(theEmployee instanceof PartTimeEmployee){
        PartTimeEmployee tempEmp = (PartTimeEmployee)theEmployee;
        double tempEmpSal = tempEmp.calcAnnualIncome();
        FullTimeEmployee fte = new FullTimeEmployee(theEmployee.getEmployeeNumber(),theEmployee.getEmployeeFirstName(),theEmployee.getEmployeeLastName(),
        theEmployee.getEmployeeSex(),theEmployee.getEmployeeWorkLocation(),theEmployee.getDeductionRate(),tempEmpSal);
        mainjframe.theHash.removeFromTable(theEmployee.getEmployeeNumber());
        new EditingEmployee(fte).setVisible(true);
        this.dispose();
        }}
        catch (Exception e){
        JOptionPane.showMessageDialog(null,"Error 404! An Error has Occured...");
        }
    }//GEN-LAST:event_fullTimeChangeActionPerformed

    private void partTimeChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partTimeChangeActionPerformed
        try{
        if (theEmployee instanceof PartTimeEmployee){
        JOptionPane.showMessageDialog(null,"This employee is already a part time employee!");
        }
        else if(theEmployee instanceof FullTimeEmployee){
        PartTimeEmployee pte = new PartTimeEmployee(theEmployee.getEmployeeNumber(),theEmployee.getEmployeeFirstName(),theEmployee.getEmployeeLastName(),
        theEmployee.getEmployeeSex(),theEmployee.getEmployeeWorkLocation(),theEmployee.getDeductionRate(),0,0,0);
        mainjframe.theHash.removeFromTable(theEmployee.getEmployeeNumber());
        new EditingEmployee(pte).setVisible(true);
        this.dispose();
        }}
        catch (Exception m){
        JOptionPane.showMessageDialog(null,"Error 404! An Error has Occured...");
        }
    }//GEN-LAST:event_partTimeChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserTypeChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserTypeChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserTypeChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserTypeChange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserTypeChange(theEmployee).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fullTimeChange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton partTimeChange;
    // End of variables declaration//GEN-END:variables
}
